<a href="https://colab.research.google.com/github/Kedarsinh01/python/blob/main/numpyday1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#LIST:-
        1. MORE MEMORY
        2. BOTH HETROGENIOUS AND HOMOGENIOUS ELEMENTS
        3. SLOWER THAN ARRAY
#ARRAY:-
        1. LESS MEMORY
        2. ONLY HOMOGENIOUS ELEMENTS
        3. FASTER THAN LIST


#IF WE PASS HETRO ELEMENTS IN ARRAY IT WILL CONVERT THE HOMO ELEMENTS INTO HETRO DATATYPE BASED ON ITS BYTE CODE

In [ ]:
import numpy as np

In [ ]:
a=[1,2,3,4,5]
x=np.array(a)
print(type(a))
print(type(x))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
x.dtype

dtype('int64')

In [ ]:
y=[1,2,3,4,5,6,'hiii']
z=np.array(y)
z.dtype                 #ALL INT WILL CONVERT INTO STRING DTYPE
print(z)

['1' '2' '3' '4' '5' '6' 'hiii']


In [ ]:
z.ndim

1

In [ ]:
#ZERO DIMENSION ARRAY
x=np.array(45)
print(x)
print(x.ndim)

45
0


In [ ]:
#ONE DIMENSION ARRAY
x=np.array([1,2,3,4,5])
print(x)
print(x.ndim)

[1 2 3 4 5]
1


In [ ]:
#TWO DIMENSION ARRAY
x=np.array([[1,2,3],[4,5,6]])
print(x)
print(x.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
#SHAPE OF ARRAY
x=np.array([[1,2,3],[4,5,6]])
print(x.shape)

(2, 3)


In [ ]:
#SHAPE OF ARRAY
a=np.array([1,2,3,4,50])
print(a.shape)

(5,)


#TYPE:
      1.it is inbuilt class formate (function)
      2.shows what data is present
      3.
#DTYPE:
      1.it is property
      2.show datatype present inside
      3.

In [ ]:
#RESHAPE OF ARRAY
x=np.array([1,2,3,4,5,6])
print(x.shape)
a=x.reshape(2,3)         #method
print(a)
print(a.shape)

(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
#ARANGE IN ARRAY    #TO PRINT THE SEQUENCE OF ELEMENTS
x=np.arange(1,20,2.5)
print(x)

[ 1.   3.5  6.   8.5 11.  13.5 16.  18.5]


In [ ]:
#LINSPACE IN ARRAY
x=np.linspace(1,20,10,retstep=True)             #(RETSTEP=TRUE):- IT CALCULATES THE DIFFERENCE BETWEEN THE NUMBERS
print(x)                                        #FORMULA TO CALCULATE LINESPACE:- END.NO - START.NO/NUM-1

(array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]), 2.111111111111111)


In [ ]:
#RANDINT IN ARRAY
x=np.random.randint(1,100,3)             #
print(x)


[98 83 84]


In [ ]:
#RANDN IN ARRAY
x=np.random.randn(1,2,3)
print(x)

[[[ 0.59141795  1.02930832 -0.58670426]
  [ 0.52687525 -1.8086207   0.43214718]]]


In [ ]:
#RAND IN ARRAY
x=np.random.rand(2)
print(x)

[0.10420501 0.89579901]


In [ ]:
#CHOICE IN ARRAY
x=[1,2,3,'True','False',2+3j]
x=np.random.choice(x)
print(x)

2


In [ ]:
#SHUFFLE IN ARRAY
x=[1,2,3,'True','False',2+3j]
np.random.shuffle(x)
print(x)

[3, 1, 2, (2+3j), 'True', 'False']


In [ ]:
#CONVERT SINGLE DIMENSION INTO 33 DIMENSION
x=np.array([1,2,3,4],ndmin=32)     #NDMIN:- MINIMUM DIMENSION OF ARRAY IT CONVERTS UPTO 32
print(x)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


#ADDING ELEMENTS IN ARRAY:
1.APPEND()

2.INSERT()

#DELETE ELEMENTS IN ARRAY:
1.DELETE()

In [ ]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [ ]:
#ADD ELEMENT BY:- APPEND()
b=np.append(a,[7,8,9])
print(b)

[1 2 3 4 5 6 7 8 9]


In [ ]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#ADDING SINGLE DIMENSION ARRAY IN MULTI-DIMENSION ARRAY:-
c=np.append(b,[[9,10,11,12]])   #CONVERT MULTI-DIMENSION INTO SINGLE DIMENSION
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
c=np.array([1,2,3,4,5])
print(c)

[1 2 3 4 5]


In [ ]:
#INSERT ELEMENT IN ARRAY
d=np.insert(c,2,30)        #INSERT ELEMENTS AT PERTICULAR POSITION AND SHIFTING PREVIOUS ELEMENT TO NEXT POSITION
print(d)

[ 1  2 30  3  4  5]


In [ ]:
#INSERT SINGLE ELEMENT IN BETWEEN TWO POSITION:
e=np.insert(c,[2,4],[30])             #[2,4]:- POSITION
print(e)

[ 1  2 30  3  4 30  5]


In [ ]:
#DELETE ELEMENT FROM ARRAY:
f=np.delete(c,2)        #(C,2):- 2 IS POSITION OF THE ELEMENT
print(f)
print(c)

[1 2 4 5]
[1 2 3 4 5]


In [ ]:
#FETCH THE ELEMENT POSITON IN ARRAY:
n=np.array([10,11,12,13,14,15,13])
print(np.where(n==13))              #USING 'WHERE' CLAUSE TO FILTER THE CONDITION AND DISPLAY THE ELEMENT PRESENT IN THE ARRAY

(array([3, 6]),)


In [ ]:
m=np.where(n==13)
print(m)

(array([3, 6]),)


In [ ]:
m=np.where(n==100)      #IF ELEMENT IS NOT PERSENT IN THE ARRAY IT WILL DISPLAY EMPTY LIST
print(m)

(array([], dtype=int64),)


In [ ]:
#SPLIT THE ELEMENT IN ARRAY:
a=np.array([10,11,12,13,14,70,80,90,100])
print(a)

[ 10  11  12  13  14  70  80  90 100]


In [ ]:
#SPLIT ARRAY IN NO. OF PARTS:
b=np.array_split(a,2)
print(b)

[array([10, 11, 12, 13, 14]), array([ 70,  80,  90, 100])]


In [ ]:
#SPLIT ARRAY IN NO. OF PARTS:
b=np.array_split(a,10)   #IF THE ARRAY IS NOT HAVING ELEMENTS IT WILL DISPLAY EMPTY LIST
print(b)

[array([10]), array([11]), array([12]), array([13]), array([14]), array([70]), array([80]), array([90]), array([100]), array([], dtype=int64)]


In [ ]:
#CHANGE ARRAY DATATYPE:INT,FLOAT,COMPLEX,BOOL
a=np.asarray([10,11,12,13,14,15],dtype=float)
print(a)

[10. 11. 12. 13. 14. 15.]


In [ ]:
#FLATER IN ARRAY:
x=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(x)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [ ]:
y=x.flatten()   #CONVERT MULTI-DIMENSION INTO SINGLE DIMENSION FORMATE
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
y=x.flatten(order='F')   #ORDER:- IT IS USED TO ARRANGEE THE ARRAY ELEMENT IN ROW('C')/COLUMN('F')
print(y)

[ 1  6 11  2  7 12  3  8 13  4  9 14  5 10 15]


In [ ]:
#PRINT UNIQUE ELEMENTS IN ARRAY:
d=np.array([1,0,2,0,3,4,0,5,9,6,7,8,9,3,3])
y=np.unique(d)
print(d)
print(y)


[1 0 2 0 3 4 0 5 9 6 7 8 9 3 3]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
d=np.array([1,0,2,0,3,4,0,5,9,6,7,8,9,3,3])
y=np.unique(d,return_index=True,return_counts=True)
#return_index=True:- PRINTS THE ELEMENT WITH POSITON
#return_counts=True:- PRINTS NO. OF ELEMENT REPETED
print(y)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 1,  0,  2,  4,  5,  7,  9, 10, 11,  8]), array([3, 1, 1, 3, 1, 1, 1, 1, 1, 2]))


#MATRIX FORMATE
1.ZEROS()

2.ONES()

3.EYE()/IDENTITY()

4.FULL()

In [ ]:
#ZERO MATRIX:
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#ONCE MATRIX:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#EYE/IDENTITY MATRIX:
a=np.eye(4,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#FULL MATRIX:
a=np.full((2,3),'a')     #'a':-IT IS ELEMENT THAT IS DISPLAY IN THE MATRIX FORMATE
print(a)


[['a' 'a' 'a']
 ['a' 'a' 'a']]
