<a href="https://colab.research.google.com/github/Kedarsinh01/python/blob/main/numpyday0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#arithmetic operation on array numpy

In [ ]:
import numpy as np
a=np.array([2,3,4,5,6,7,8,9])
b=np.array([1,2,3,4,5,6,7,8])
print(np.add(a,b))    #[ 3  5  7  9 11 13 15 17]
print(np.subtract(a,b)) #[1 1 1 1 1 1 1 1]
print(np.multiply(a,b))#[ 2  6 12 20 30 42 56 72]
print(np.divide(a,b)) #[2.         1.5        1.33333333 1.25       1.2        1.16666667   1.14285714 1.125     ]
print(np.mod(a,b))
print(np.power(a,b))

[ 3  5  7  9 11 13 15 17]
[1 1 1 1 1 1 1 1]
[ 2  6 12 20 30 42 56 72]
[2.         1.5        1.33333333 1.25       1.2        1.16666667
 1.14285714 1.125     ]
[0 1 1 1 1 1 1 1]
[       2        9       64      625     7776   117649  2097152 43046721]


In [ ]:
import numpy as np
a=np.array([2,3,4,5,6,7,8,9])
b=np.array([1,2,3,4,5,6,7,8])
c=np.array([12,34,465,67,87,12,21,12])
print(np.add(a,b,c))

[ 3  5  7  9 11 13 15 17]


In [ ]:
#scalar operation
# import numpy as np
a=np.array([2,3,4,5,6,7,8,9])
print(a+5)
print(a-5)
print(a*5)
print(a/5)
print(a%5)
print(a**5)


[ 7  8  9 10 11 12 13 14]
[-3 -2 -1  0  1  2  3  4]
[10 15 20 25 30 35 40 45]
[0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[2 3 4 0 1 2 3 4]
[   32   243  1024  3125  7776 16807 32768 59049]


In [ ]:
a=np.array([2,3,4,5,6,7,8,9])
b=np.array([1,2,3,4,5,6,4,5])
print(np.array_equal(a,b)) #False
print(np.array_equal(a,a)) #True

False
True


In [ ]:
a=np.array([2,3,4,5,6,7,8,9])
b=np.array([2,3,4,5,6,7,8,9])
# print(np.sin(a,b)) error cannot cast
# print(np.cos(a,b))   error cannot cast
# print(np.tan(a,b))   error cannot cast
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866
  0.98935825  0.41211849]
[-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029  0.75390225
 -0.14550003 -0.91113026]
[-2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619  0.87144798
 -6.79971146 -0.45231566]
